// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX2WwPApfemU3hwi2w1-X7pzs8MtcrXRw',
    appId: '1:218332612587:web:1f36001874c9603eba3bae',
    messagingSenderId: '218332612587',
    projectId: 'login-page-f743f',
    authDomain: 'login-page-f743f.firebaseapp.com',
    storageBucket: 'login-page-f743f.appspot.com',
    measurementId: 'G-HW6QMC9X2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc4xDpYIjHyvQarB2l_jYK0Wzih9HE6Jw',
    appId: '1:218332612587:android:ee7fe5ff30b4b273ba3bae',
    messagingSenderId: '218332612587',
    projectId: 'login-page-f743f',
    storageBucket: 'login-page-f743f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMuhycSd6bHBz-ryxSYkWvqtEGwHVJo4Y',
    appId: '1:218332612587:ios:810a6615f50e01ccba3bae',
    messagingSenderId: '218332612587',
    projectId: 'login-page-f743f',
    storageBucket: 'login-page-f743f.appspot.com',
    iosBundleId: 'com.example.fireLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMuhycSd6bHBz-ryxSYkWvqtEGwHVJo4Y',
    appId: '1:218332612587:ios:810a6615f50e01ccba3bae',
    messagingSenderId: '218332612587',
    projectId: 'login-page-f743f',
    storageBucket: 'login-page-f743f.appspot.com',
    iosBundleId: 'com.example.fireLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX2WwPApfemU3hwi2w1-X7pzs8MtcrXRw',
    appId: '1:218332612587:web:a42308554f3b55f3ba3bae',
    messagingSenderId: '218332612587',
    projectId: 'login-page-f743f',
    authDomain: 'login-page-f743f.firebaseapp.com',
    storageBucket: 'login-page-f743f.appspot.com',
    measurementId: 'G-GT92XRHYKY',
  );

}